title : Dev Environment


default_loglevel: &default_loglevel "warning" # global loglevel add loglevel to each module to overwrite for spec module
compiler:
  loglevel: *default_loglevel
  repo: "DslRepository"
  validator: "DummyValidator"
  manipulators:

    - "DummyManipulator"

  dsl_repository:

    dir: "data/config/instance.yaml"

  spec_repository:

    dir: "data/jssp_instances/ft06"

env:
  loglevel: *default_loglevel
  observation_factory: "TasselObservationBinaryActionFactory"
  reward_factory: "BinaryActionJsspReward"
  action_factory: "BinaryJobActionFactory"
  render_engine: "plot_gant"
  max_time_fct: 2

state_machine:
  loglevel: *default_loglevel
  middleware: "SimpleEventBasedJsspMiddleware"
  action_factory: "BinaryJobActionFactory"

action_factory:
  binary_job_action_factory:
    loglevel: *default_loglevel

middleware:
  simple_event_based_jssp_middleware:
    loglevel: *default_loglevel

observation_factories:
  tassel_observation_binary_action_factory:
    loglevel: *default_loglevel

reward_factories:
  binary_action_jssp_reward:
    loglevel: *default_loglevel
    sparse_bias: 1 #[0,inf] float
    dense_bias: 0.1 #[0,inf] float
    truncation_bias: -10000 #[-inf,0] float


render_engines:
  plot_gant:
    loglevel: *default_loglevel
  backend_config:
    backend: auto_selection # auto_selection, show, save
    dir: "data/plots"
    format: "png" # png or html
    width: 500
    height: 500
